- name: install nginx
  ansible.builtin.package: #HETEROGENOUS MODULE IT WORKS FOR ALL DISTRIBUTIONS
    name: nginx
    state: present
- name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove existed html directory
  ansible.builtin.file:
    path: /user/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /user/share/nginx/html
    state: directory

- name: download frontend  code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: extract the frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy expense.conf file
  ansible.builtin.template:
    src: expense.conf.J2
    dest: /etc/nginx/default.d/expense.conf

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted